version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8000}:8000
    environment:
      NODE_ENV: ${NODE_ENV} # Changed to production
      PORT: ${PORT:-8000}
      MONGODB_URL: ${MONGODB_URL} # Will come from Render environment variables
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION_MINUTES: ${JWT_ACCESS_EXPIRATION_MINUTES:-15}
      JWT_REFRESH_EXPIRATION_DAYS: ${JWT_REFRESH_EXPIRATION_DAYS:-30}
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: ${JWT_RESET_PASSWORD_EXPIRATION_MINUTES:-10}
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: ${JWT_VERIFY_EMAIL_EXPIRATION_MINUTES:-10}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
    restart: unless-stopped

  # For Render, you might want to use their managed MongoDB service instead of running your own
  # So you can remove or comment out the mongo and mongo-express services
