services:
  - type: web
    name: your-app-name
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: docker compose -f docker-compose-render.yml -f docker-compose-prod.yml up
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      # Other environment variables will be set in Render dashboard
