name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Run Tests
        run: npm test

      # Add Docker setup steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Add Docker Compose setup
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Now validate Docker Compose files
      - name: Validate Docker Compose
        run: docker-compose -f docker-compose-render.yml -f docker-compose-prod.yml config

  cd:
    needs: ci # This ensures CD only runs if CI passes
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on main branch

    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }} # Find this in the URL of your Render service
          api-key: ${{ secrets.RENDER_API_KEY }} # Save this in the repo secrets
